3 course/1 term/СТРWП/3a/3a/3a/3a/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASPCMVC07.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.CurrentAction = "Index";
            return View("Index");
        }

        [HttpPost]
        public IActionResult Sum(float x, float y)
        {
            float result = x + y;
            ViewBag.Result = result;
            ViewBag.CurrentAction = "Sum";

            return View("Index");

           
        }
        public IActionResult Sum()
        {
            ViewBag.CurrentAction = "Sum";
            return View("Index");
        }

        [HttpPost]
        public IActionResult Sub(float x, float y)
        {
            float result = x - y;
            ViewBag.Result = result;
            ViewBag.CurrentAction = "Sub";
            return View("Index");
        }
        public IActionResult Sub()
        {
            ViewBag.CurrentAction = "Sub";
            return View("Index");
        }

        [HttpPost]
        public IActionResult Mul(float x, float y)
        {
            float result = x * y;
            ViewBag.Result = result;
            ViewBag.CurrentAction = "Mul";
            return View("Index");
        }

        public IActionResult Mul()
        {
            ViewBag.CurrentAction = "Mul";
            return View("Index");
        }

        [HttpPost]
        public IActionResult Div(float x, float y)
        {
            if (y != 0)
            {
                float result = x / y;
                ViewBag.Result = result;
                ViewBag.CurrentAction = "Div";
            }
            else
            {
                ViewBag.Error = "Division by zero is not allowed.";
                ViewBag.CurrentAction = "Div";
            }
            return View("Index");
        }
        public IActionResult Div()
        {
            ViewBag.CurrentAction = "Div";
            return View("Index");
        }
    }
}

3 course/1 term/СТРWП/3a/3a/3a/3a/Views/Calc/Calc.cshtml
<input type="number" name="x" id="x" value="@ViewBag.x" />

<input type="number" name="y" id="y" value="@ViewBag.y" />

3 course/1 term/СТРWП/3a/3a/3a/3a/Views/Calc/CalcLink.cshtml
    <div>
        <a href="@Url.Action("Sum", "Calc")">Add</a>
        <a href="@Url.Action("Sub", "Calc")">Sub</a>
        <a href="@Url.Action("Mul", "Calc")">Mul</a>
        <a href="@Url.Action("Div", "Calc")">Div</a>
    </div>

3 course/1 term/СТРWП/3a/3a/3a/3a/Views/Calc/Index.cshtml
@{
    Layout = null;
    string currentAction = ViewBag.CurrentAction;
    string press = (string)ViewBag.press;

    if (!String.IsNullOrEmpty(press))
    {
        switch (press)
        {
            case "+":
                currentAction = "Sum";
                break;
            case "-":
                currentAction = "Sub";
                break;
            case "*":
                currentAction = "Mul";
                break;
            case "/":
                currentAction = "Div";
                break;
            default:
                currentAction = "Index";
                break;
        }
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calc</title>
</head>
<body>
@await Html.PartialAsync("CalcLink")
    @if (currentAction == "Index")
    {
        <p>Please select an operation to perform.</p>
    }
    else
    {
        using (Html.BeginForm(currentAction, "Calc", FormMethod.Post))
        {

            @await Html.PartialAsync("Calc")
            
               <button type="submit" name="press" value="@press">@currentAction</button>
        }
    }

    @if (!String.IsNullOrEmpty(ViewBag.Error))
    {
        <p>@ViewBag.Error</p>
    }
    @if (ViewBag.Result != null)
    {
        <p>Result: @ViewBag.Result</p>
    }
</body>
</html>